### ISSUE TITLE
Is this still working?

### ISSUE THREAD

**Issue by jadehawk** [skleeschulte/basic-to-passport-auth-http-proxy#3]
I ask because I can't get it to work and if trying to access https://d.docs.live.net/ directly gives 404 error. Thank You..

**Comment by jbuller** [comment]
I have also encountered this error. Any help appreciated

**Comment by sounds2k** [comment]
yes it is, however you may have fallen into the same trap I did - forgetting to set the local port to 3000. Open docker - go to "container" and double-click on the proxy, under "port settings" near the bottom the local port and container port should _both_ be 3000 (mine was showing 32768 as the local port).  If this is what you see - close the properties window and stop the container by clicking on the slider at the right of the proxy server name. When it's stopped, select "edit", switch to the "port settings" tab - you'll most likely see that the "local port" is set to Auto. Click where it says that, enter 3000 as the port number and press enter. Then click on "Apply", restart the container and try again - hopefully it should now work :-)

**Comment by jbuller** [comment]
I wasn't using docker, just the command line to try getting the node.js script to run.
The Synology terminal port is set to 2299.

**Comment by sounds2k** [comment]
OK, so slightly different from how I had it configured using docker. What environment variable did you use to set the port to 2299 ... as there's both a local and container port number - and what are you using as the server address in the application set to use WebDAV?
